### PR TITLE
update raml-js-parser-2 version

### PR DESCRIPTION
**Pull request by jenschude**
fix typings for ES5 target using recent raml-js-parser-2

### CODE REVIEW

**Comment by jenschude** [comment]
This would solve #15

**Comment by sichvoge** [comment]
Hi @jayS-de. Bumping the parser is not the only change you would need to do. It seems that there is a bit more to that. For example, if you want to expand libraries as well you would need to execute `expand(true)` instead of `expand()`. There might be more that needs to change with regards to all the different changes that were introduced since the beta.

**Comment by jenschude** [comment]
Actually in my local project I just overwrote the raml-parser version. I had no issues with that yet. But it fixed a lot of problems with json schema references

**Comment by jenschude** [comment]
I added an argument to expand libraries. For 0.8 RAML the argument will have no meaning, for 1.0 RAML libraries would be expanded

**Comment by sichvoge** [comment]
Can you do me a last favour. Can you add a test for this RAML project https://github.com/raml-org/raml-examples/tree/master/others/world-music-api. If that successful gets through and the raml-generator output is whats expected, than I am good to merge your PR. :)

**Comment by jenschude** [comment]
@sichvoge I have some questions about testing this.

First how to best integrate the example? As git submodule, subtree or directly commit?

Second the loading and expanding of the API definition to JSON is done inside the bin.ts using the functionality of the raml-js-parser-2. So it's kind of pointless to test inside this package if another package can correctly read the RAML definition into Json. To actually make it somehow work, I just extracted the expansion inside bin.ts to a function and exported the function. Now I could compare direct expansion against the expansion from the bin.ts

```
import test = require('blue-tape')
import {expand} from './bin'
import {join}  from 'path'
import parser = require('raml-1-parser')

test('console command', t => {
  t.test('expand raml', t => {
    const musicRaml = join(__dirname, '../test/world-music-api/api.raml');

    const api = parser.loadApiSync(musicRaml);
    const api2 = parser.loadApiSync(musicRaml);
    t.deepEqual(
      expand(api, true),
      api2.expand(true).toJSON()
    );

    t.end();
  })
})
```

But as you can see it's kind of pointless to test functionality of a different package, as it is only testing that you pass an argument.

Another possibility would be to move the expanding to the index.ts or to expand always. I'm unsure what could be the best way. Maybe you have a suggestion

**Comment by sichvoge** [comment]
Just to give you some feedback here so that you know I saw your message ;) 
1. I would directly commit the example in here.
2. Thats something I'd need to think about as well. Currently swamped but will take some time on Monday.

**Comment by jenschude** [comment]
I think I found a working and usable solution. Added the example as you suggested directly to the repository. And added a spec test case which loads and expands the raml definition and then tries to call the generator object

**Comment by sichvoge** [comment]
👍 looks good to me. thanks!

**Pull request merged**
